// app/layout.tsx (서버 컴포넌트로 변경)
import {Avatar, AvatarFallback, AvatarImage} from '@/components/ui/avatar'
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuLink
} from '@/components/ui/navigation-menu'
import {Button} from '@/components/ui/button'
import {getCookie, deleteCookie} from 'cookies-next'
import {fetchCurrentUser} from '@/services/auth'
import {RiDashboardFill} from 'react-icons/ri'
import {cookies} from 'next/headers' // 서버에서 쿠키를 가져오기 위한 Next.js 내장 모듈
import type {Metadata} from 'next'

// These styles apply to every route in the application
import './global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  // 서버 측에서 쿠키를 가져와 토큰을 확인하고 사용자 정보를 불러옵니다.
  const cookieStore = cookies()
  const token = (await cookieStore).get('token')?.value

  // 사용자 정보를 불러옵니다. (서버에서만 처리)
  let username = ''
  if (token) {
    try {
      const user = await fetchCurrentUser(token)
      username = user.name || user.email
    } catch (err) {
      console.error('사용자 정보 불러오기 실패:', err)
    }
  }

  const handleLogout = () => {
    deleteCookie('token')
    deleteCookie('username')
  }

  return (
    <html lang="en">
      <body className="w-full h-full">
        <div className="flex flex-row w-full h-full">
          <NavigationMenu className="flex justify-between min-w-full p-4 bg-white shadow-lg h-14">
            <NavigationMenuList className="text-2xl font-bold">
              <NavigationMenuLink
                className="flex flex-row items-center font-apple"
                href="/">
                <RiDashboardFill className="mr-2" />
                NNMM
              </NavigationMenuLink>
            </NavigationMenuList>
            <NavigationMenuList className="flex items-center space-x-4">
              {username ? (
                <span className="text-xl text-gray-700 font-apple">{username} 님</span>
              ) : (
                <span className="text-xl text-gray-400 font-apple">게스트</span>
              )}
              <NavigationMenuLink onClick={handleLogout}>
                <Button className="mr-3 font-apple text-lg">로그아웃</Button>
              </NavigationMenuLink>
              <NavigationMenuLink href="/mypage/mypage">
                <Avatar className="mr-2">
                  <AvatarImage
                    src="https://avatars.githubusercontent.com/u/118759932?v=4&size=64"
                    alt="사용자 아바타"
                  />
                  <AvatarFallback>CNs</AvatarFallback>
                </Avatar>
              </NavigationMenuLink>
            </NavigationMenuList>
          </NavigationMenu>
          <main className="flex-grow mt-14 p-4 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  )
}
