import {Avatar, AvatarFallback, AvatarImage} from '@/components/ui/avatar'
// import React, {useEffect, useState} from 'react'
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuLink
} from '@/components/ui/navigation-menu'
import {Button} from '@/components/ui/button'
import {getCookie, deleteCookie} from 'cookies-next'
// import {useRouter} from 'next/navigation' // Next.js의 app router에서 사용하는 useRouter
import {fetchCurrentUser} from '@/services/auth'
import {RiDashboardFill} from 'react-icons/ri'
import type {Metadata} from 'next'

// These styles apply to every route in the application
import '../global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({children}: {children: React.ReactNode}) {
  // const [username, setUsername] = useState('')
  // const router = useRouter()

  // useEffect(() => {
  //   const loadUser = async () => {
  //     const token = await Promise.resolve(getCookie('token'))
  //     if (!token || typeof token !== 'string') return

  //     try {
  //       const user = await fetchCurrentUser(token)
  //       setUsername(user.name || user.email)
  //     } catch (err) {
  //       console.error('사용자 정보 불러오기 실패:', err)
  //     }
  //   }

  //   loadUser()
  // }, [])

  // const handleLogout = () => {
  //   deleteCookie('token')
  //   deleteCookie('username')
  //   router.push('/auth/signin') // app router에서 push 사용
  // }

  return (
    <html lang="en">
      <body className="w-full h-full">
        <div className="flex flex-row w-full h-full">
          <NavigationMenu className="flex justify-between min-w-full p-4 bg-white shadow-lg h-14">
            <NavigationMenuList className="text-2xl font-bold">
              <NavigationMenuLink
                className="flex flex-row items-center font-apple"
                href="/">
                <RiDashboardFill className="mr-2" />
                NNMM
              </NavigationMenuLink>
            </NavigationMenuList>
            <NavigationMenuList className="flex items-center space-x-4">
              {/* {username ? (
                <span className="text-xl text-gray-700 font-apple">{username} 님</span>
              ) : (
                <span className="text-xl text-gray-400 font-apple">게스트</span>
              )} */}

              <NavigationMenuLink>
                <Button className="mr-3 font-apple text-lg">로그아웃</Button>
              </NavigationMenuLink>
              <NavigationMenuLink href="/mypage/mypage">
                <Avatar className="mr-2">
                  <AvatarImage
                    src="https://avatars.githubusercontent.com/u/118759932?v=4&size=64"
                    alt="사용자 아바타"
                  />
                  <AvatarFallback>CNs</AvatarFallback>
                </Avatar>
              </NavigationMenuLink>
            </NavigationMenuList>
          </NavigationMenu>
        </div>
        <main>{children}</main>
      </body>
    </html>
  )
}
